feh --no-fehbg --bg-fill ~/.config/background.jpg
picom -b
polybar mybar 2>&1 | tee -a /tmp/polybar.log &
command -v autorandr && autorandr -c
xautolock -time 15 -locker 'systemctl suspend' &
exec xmonad
